# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Phillip Google
blurb: Not Engineer @ Google ¯\_(ツ)_/¯
email: somethingthathurtsbda@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A website built to test out markdown, applying content created 
  with html and seeing what inharent diffenerces are created by 
  uding this new process.
repository: git@github.com:bdfairbanks/bdfairbanks.github.io.git

# Build settings - DO NOT EDIT, UNLESS YOU KNOW WHAT YOU'RE DOING.
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
